
DB = "database/db.sqlite"
#TABLAS
TBL_ARTEFACTOS = "artefactos"
TBL_ENTIDAD_EDUCATIVA = "entidad_educativa"
TBL_PROVINCIA="provincias"
TBL_DEPARTAMENTO="departamentos"
TBL_LOCALIDAD="localidades"

#CAMPOS

F_ARTEFACTOS_ID = "id_artefacto"
F_ARTEFACTOS_ARTEFACTO = "artefacto"
F_ARTEFACTOS_WATTS = "watts"
F_ARTEFACTOS_IMG_NAME = "imagen"

F_ENTIDAD_EDU_ID_EDU = "Id_edu"
F_ENTIDAD_EDU_DENOMINACION = "denominacion"
F_ENTIDAD_EDU_CUE = "cue"
F_ENTIDAD_EDU_ID_PROV = "id_prov"
F_ENTIDAD_EDU_ID_DPTO = "id_dpto"
F_ENTIDAD_EDU_ID_LOCALIDAD = "id_localiad"
F_ENTIDAD_EDU_FECHA_ALTA = "fecha_alta"

F_PROVINCIA_ID="id_prov"
F_PROVINCIA_COD_PROV= "cod_prov"
F_PROVINCIA_NOM ="provincia"

F_DEPARTAMENTO_ID="id_dpto"
F_DEPARTAMENTO_COD = "cod_dpto"
F_DEPARTAMENTO_COD_PROV= "cod_prov"
F_DEPARTAMENTO_NOM ="departamento"

F_LOCALIDAD_ID= "id_localidad"
F_LOCALIDAD_COD = "cod_localidad"
F_LOCALIDAD_COD_DPTO = "cod_dpto"
F_LOCALIDAD_COD_PROV = "cod_prov"
F_LOCALIDAD_NOM = "localidad"
#SCRIPTS

CREATE_TBL_ARTEFACTOS = f"""
    CREATE TABLE IF NOT EXISTS {TBL_ARTEFACTOS} (
        { F_ARTEFACTOS_ID } INTEGER PRIMARY KEY AUTOINCREMENT,
        { F_ARTEFACTOS_ARTEFACTO} TEXT,
        { F_ARTEFACTOS_WATTS} REAL,
        { F_ARTEFACTOS_WATTS} TEXT)"""

CREATE_TBL_ENT_EDU = f"""
    CREATE TABLE IF NOT EXISTS { TBL_ENTIDAD_EDUCATIVA } (
        { F_ENTIDAD_EDU_ID_EDU} INTEGER PRIMARY KEY AUTOINCREMENT,
        { F_ENTIDAD_EDU_DENOMINACION} TEXT,
        { F_ENTIDAD_EDU_CUE} TEXT,
        { F_ENTIDAD_EDU_ID_PROV} INTEGER,
        { F_ENTIDAD_EDU_ID_DPTO } INTEGER,
        { F_ENTIDAD_EDU_ID_LOCALIDAD} INTEGER,
        { F_ENTIDAD_EDU_FECHA_ALTA} TEXT
    )
"""
CREATE_TBL_PROVINCIA= f"""
    CREATE TABLE IF NOT EXISTS {TBL_PROVINCIA} (
        {F_PROVINCIA_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
        {F_PROVINCIA_COD_PROV} INTEGER,
        {F_PROVINCIA_NOM} TEXT 
    )
"""
CREATE_TBL_DPTO = f"""
    CREATE TABLE IF NOT EXISTS {TBL_DEPARTAMENTO} (
        {F_DEPARTAMENTO_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
        {F_DEPARTAMENTO_COD} INTEGER,
        {F_DEPARTAMENTO_COD_PROV} INTEGER,
        {F_DEPARTAMENTO_NOM} TEXT         
    )
"""
CREATE_TBL_LOCALIDAD = f"""
    CREATE TABLE IF NOT EXISTS {TBL_LOCALIDAD} (
        {F_LOCALIDAD_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
        {F_LOCALIDAD_COD} INTEGER,
        {F_LOCALIDAD_COD_DPTO} INTEGER,
        {F_LOCALIDAD_COD_PROV} INTEGER,
        {F_LOCALIDAD_NOM} TEXT         
    )
"""
